language: cpp
sudo: required	
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - libgtest-dev
before_script:
  - install -d gtest_build
  - pushd gtest_build
  - cmake -DCMAKE_CXX_COMPILER=gcc /usr/src/gtest/
  - make
  - sudo cp *.a /usr/lib
  - popd
script:
  - install -d build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=gcc ..
  - make